### ISSUE TITLE
TypeError: fflate.ungzipSync is not a function

### ISSUE THREAD

**Issue by neuropacman** [rii-mango/NIFTI-Reader-JS#45]
I am experiencing an issue with a the "fflate" dependency for nifti-reader-js@0.6.8:

TypeError: fflate.decompressSync is not a function
    at Object.decompress (nifti.ts:119:1)
    at fetchAndProcessNiftiData (cornerstoneNiftiImageLoader.js:71:1)

This seems to be an issue with how 'fflate' package is being included in nifti.ts. I have attempted to create a patch but was unsuccessful. In the fflate version (fflate@0.7.4) being used by nifti-reader-js, "decompressSync" is a valid method. 

I have attempted using different versions of fflate and modifying how fflate is being included, but have not had any luck.

Perhaps I am doing something wrong here, but I have used fflate.decompressSync in other contexts with v0.7.4 successfully before.

**Comment by wvalenzuela** [comment]
I have similar issue update "nifti-reader-js": "0.7.1"
